### PR TITLE
added threading and read from YAML

### PR DESCRIPTION
**Pull request by rootVIII**
Okay the time is cut down to about 4 or 5 seconds with the threading (originally it was 12-13 seconds for me).

I had to add to extra imports to your setup.py (pyyaml and jinja2).

The new yaml file has all the links etc and uses Jinja2... You can add links dynamically onto that yaml file now and place {{ username }} wherever the username belongs in the URL.

I hardly touched anything on utils.py and didn't mess with your GET requests etc... But if you want to add bs4 or scrape in the future, you can add whatever you want to that file and it will still be threaded.

Overall I'm pretty happy with these changes.

EDIT: Added realpath to yaml so that you can still run search4 from any location in your shell/terminal. Added timeout=1.0 on requests.get (but later removed the timeoutt: it caused false reading on Reddit)

### CODE REVIEW

**Comment by ghost** [comment]
Nice!

But, as the installation stated in readme, it won't work that way?

**Comment by ghost** [comment]
And @7rillionaire had class tests :^) so he was not able to push commits. Probably in one hour he should push #9

**Comment by rootVIII** [comment]
Well it's up to you :) I just installed on my Kali Machine and also reinstalled on my Ubuntu machine. It's working good! And fast too...

**Comment by ghost** [comment]
Installing search4 should be done like in the readme?

`pip install git+https://github.com/7rillionaire/Search4`

This is causing some issues in Termux. 

Idk why @NeverMine17 @rootVIII @7rillionaire

**Comment by rootVIII** [comment]
Oh I hadn’t tried like that. I cloned and then navigated to the project, and then ran ` pip install -e .` seems to work pretty good. I’ll try directly from the github  URL though . Also make sure your pip is is pointing to python3 ... My actual command for Ubuntu was `pip3 isntall -e .`

**Comment by rootVIII** [comment]
Ah I see what you are saying... it can't find the YAML file when installed through git+https://github.com/7rillionaire/Search4

Let me see if I can fix that.

**Pull request merged**
